import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar/Navbar'
import { ThemeProvider } from "@/components/theme-provider"
import { Toaster } from '@/components/ui/toaster'
import Provider from '@/components/auth-provider'
import Head from 'next/head'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Auth Next',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Head>
        <link rel="shortcut icon" href="@/src/app/favicon.ico" type="image/x-icon" />
      </Head>
        <body className='bg-zinc-950'>
            <ThemeProvider
                attribute="class"
                defaultTheme="dark"
                enableSystem
                disableTransitionOnChange
                >
              <Provider>
                <Navbar/>
                <hr className='white'/>
                  {children}
              </Provider>
              <Toaster />
            </ThemeProvider>
        </body>
    </html>
  )
}
